New log file opened at Thu Jan 05 14:47:36 EST 2017 by 5936@akzysk-W370ST
Taking next connection to: 50628
New client attempting to connect on port: 50629-50628
  Address = /192.168.56.1:50628
This client on port 50629 has uuid 7850bdd4-8bd4-4166-a30a-f280d8fb5141 configName activator humanReadableName Activator protocolVersion 3 featureTags Vector()
Connected Clients: activator-7850bdd4-8bd4-4166-a30a-f280d8fb5141
Taking next connection to: 50628
New client attempting to connect on port: 50630-50628
  Address = /192.168.56.1:50628
Handshake exception on socket: 50630
sbt.impl.ipc.HandshakeException: Unable to perform handshake
	at sbt.impl.ipc.Peer.handshake(IPC.scala:46)
	at sbt.impl.ipc.MultiClientServer.<init>(IPC.scala:150)
	at sbt.server.SbtServerSocketHandler$$anon$1.run(SbtServerSocketHandler.scala:43)
Caused by: java.net.SocketException: Software caused connection abort: recv failed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.fill(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at java.io.DataInputStream.readInt(Unknown Source)
	at sbt.impl.ipc.Peer.receive(IPC.scala:95)
	at sbt.impl.ipc.Peer.handshake(IPC.scala:49)
	... 2 more
Taking next connection to: 50628
New client attempting to connect on port: 50631-50628
  Address = /192.168.56.1:50628
This client on port 50631 has uuid be546ea9-cf30-463f-bc4a-8e6762959d90 configName activator humanReadableName Activator protocolVersion 3 featureTags Vector()
Connected Clients: activator-7850bdd4-8bd4-4166-a30a-f280d8fb5141, activator-be546ea9-cf30-463f-bc4a-8e6762959d90
Taking next connection to: 50628
New client attempting to connect on port: 50634-50628
  Address = /192.168.56.1:50628
Handshake exception on socket: 50634
sbt.impl.ipc.HandshakeException: Unable to perform handshake
	at sbt.impl.ipc.Peer.handshake(IPC.scala:46)
	at sbt.impl.ipc.MultiClientServer.<init>(IPC.scala:150)
	at sbt.server.SbtServerSocketHandler$$anon$1.run(SbtServerSocketHandler.scala:43)
Caused by: java.net.SocketException: Software caused connection abort: recv failed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.fill(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at java.io.DataInputStream.readInt(Unknown Source)
	at sbt.impl.ipc.Peer.receive(IPC.scala:95)
	at sbt.impl.ipc.Peer.handshake(IPC.scala:49)
	... 2 more
Taking next connection to: 50628
New client attempting to connect on port: 50635-50628
  Address = /192.168.56.1:50628
This client on port 50635 has uuid 69361109-7106-46dc-bb16-9b0debb1db79 configName play-fork-run humanReadableName Play Fork Run protocolVersion 1 featureTags Vector()
Connected Clients: activator-be546ea9-cf30-463f-bc4a-8e6762959d90, play-fork-run-69361109-7106-46dc-bb16-9b0debb1db79
Taking next connection to: 50628
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 50628
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 50628
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 50628
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 50628
Checking to see if clients are empty...
No non-daemon clients connected after 3 min. Shutting down.
1 daemon clients are connected.
Server socket thread exiting.
1 clients open, will close them...
All client sockets have been closed.
Closing the 5936@akzysk-W370ST logs at Thu Jan 05 15:04:19 EST 2017, goodbye.
