New log file opened at Tue Apr 18 16:53:26 EDT 2017 by 1228@akzysk-W370ST
Taking next connection to: 57092
New client attempting to connect on port: 57094-57092
  Address = /192.168.56.1:57092
This client on port 57094 has uuid b0688f7c-7e3b-499d-ba64-023fe1231324 configName activator humanReadableName Activator protocolVersion 3 featureTags Vector()
Connected Clients: activator-b0688f7c-7e3b-499d-ba64-023fe1231324
Taking next connection to: 57092
New client attempting to connect on port: 57095-57092
  Address = /192.168.56.1:57092
Handshake exception on socket: 57095
sbt.impl.ipc.HandshakeException: Unable to perform handshake
	at sbt.impl.ipc.Peer.handshake(IPC.scala:46)
	at sbt.impl.ipc.MultiClientServer.<init>(IPC.scala:150)
	at sbt.server.SbtServerSocketHandler$$anon$1.run(SbtServerSocketHandler.scala:43)
Caused by: java.net.SocketException: Software caused connection abort: recv failed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.fill(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at java.io.DataInputStream.readInt(Unknown Source)
	at sbt.impl.ipc.Peer.receive(IPC.scala:95)
	at sbt.impl.ipc.Peer.handshake(IPC.scala:49)
	... 2 more
Taking next connection to: 57092
New client attempting to connect on port: 57096-57092
  Address = /192.168.56.1:57092
This client on port 57096 has uuid 248405d2-cc6a-464d-8012-06f16fc41b66 configName activator humanReadableName Activator protocolVersion 3 featureTags Vector()
Connected Clients: activator-b0688f7c-7e3b-499d-ba64-023fe1231324, activator-248405d2-cc6a-464d-8012-06f16fc41b66
Taking next connection to: 57092
New client attempting to connect on port: 57120-57092
  Address = /192.168.56.1:57092
Handshake exception on socket: 57120
sbt.impl.ipc.HandshakeException: Unable to perform handshake
	at sbt.impl.ipc.Peer.handshake(IPC.scala:46)
	at sbt.impl.ipc.MultiClientServer.<init>(IPC.scala:150)
	at sbt.server.SbtServerSocketHandler$$anon$1.run(SbtServerSocketHandler.scala:43)
Caused by: java.net.SocketException: Software caused connection abort: recv failed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.fill(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at java.io.DataInputStream.readInt(Unknown Source)
	at sbt.impl.ipc.Peer.receive(IPC.scala:95)
	at sbt.impl.ipc.Peer.handshake(IPC.scala:49)
	... 2 more
Taking next connection to: 57092
New client attempting to connect on port: 57121-57092
  Address = /192.168.56.1:57092
This client on port 57121 has uuid 32ef30f5-7009-49ee-8a48-a52913a66066 configName play-fork-run humanReadableName Play Fork Run protocolVersion 1 featureTags Vector()
Connected Clients: activator-248405d2-cc6a-464d-8012-06f16fc41b66, play-fork-run-32ef30f5-7009-49ee-8a48-a52913a66066
Taking next connection to: 57092
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 57092
